spring:
  datasource:
    # 数据库连接四要素
    url: jdbc:mysql://localhost:3306/tlias_mp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# 配置Spring事务管理的debug级别日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# 配置MyBatis的日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true    # 开启驼峰命名